baseurl: '/KicksFolio'
url: 'https://remyshift.github.io'
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
    - jekyll-remote-theme
title: KicksFolio - Privacy Policy
description: Privacy Policy of the KicksFolio application
lang: en
