baseurl: '/KicksFolio'
url: 'https://remyshift.github.io'
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
    - jekyll-remote-theme
title: KicksFolio Legal
description: Privacy Policy and Terms of Use for KicksFolio application
lang: en

# Navigation menu
navigation:
  - title: Home
    url: /KicksFolio/
  - title: Privacy Policy
    url: /KicksFolio/privacy-policy
  - title: Terms of Use
    url: /KicksFolio/terms-of-use
